import { Lexend } from "next/font/google";
import NavigationBar from "@/components/general_page/home_page/NavigationBar";

import "../globals.css";

export const metadata = {
  title: "Bất động sản",
  description: "Generated by create next app",
};

const lexendMedium = Lexend({
  variable: "--font-lexend-medium",
  subsets: ["latin"],
});

export default function TrangChuLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${lexendMedium.variable} antialiased` }>
        <NavigationBar />
        <main className="mt-[6rem]">{children}</main>
      </body>
    </html>
  );
}
